### ISSUE TITLE
Проверка лабораторной работы 4

### ISSUE THREAD

**Issue by level55** [level55/Sumprog#1]
Работу выполнил:
Щербаков Виталий Викторович
Горовенко Александр Владимирович

@evgeny-p

**Comment by evgeny-p** [comment]
1. Отсутствует цель `clean`.
1. Исполняемый и объектные файлы закоммичены в репозиторий.
1. В заголовочном файле отсутствуют [include guards](https://ru.wikipedia.org/wiki/Include_guard).
1. В данном случае семантика аргументов функции `add` очевидна, но давайте все же будем писать имена и в объявлении функции.
1. `main.c:11` нет пробела после запятой.

**Comment by level55** [comment]
Исправлено.

@evgeny-p

**Comment by evgeny-p** [comment]
1. В цели `clean` не удаляется исполняемый файл.
1. Не исправлены замечания 4 и 5.

**Comment by level55** [comment]
Вроде исправил. Правда не до конца ясно что требовалось сделать в 4 пункте.  Если требовалось прописать названия в sum.h файле, то сейчас их прописал.

@evgeny-p

**Comment by evgeny-p** [comment]
Принято.
